##
# nix-build render and open
#
# Style sheets https://github.com/citation-style-language/styles/
# @file
# @version 0.1

.PHONY: typeset

typeset:
	nix-build
	xdg-open result/companion-solver-implementation-reference.pdf
# end
