# This can be run manually like so:
#
#     gh workflow run nixpdf.yml --ref <git_branch_name>
#
name: PDF with Nix
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  render-pdf-push:
    name: Render & Push PDF with Nix
    runs-on: self-hosted
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M%S')" >> $GITHUB_ENV
    - name: Checkout repository to $GITHUB_WORKSPACE
      uses: actions/checkout@v2.3.4

    - name: Nix build
      run: nix-build

    - name: Push PDF
      uses: actions-x/commit@v2
      with:
        files: result/audit.pdf
        message: 'Freshly rendered audit.pdf at $${{ env.NOW }}'
        name: GitHub Actions Autocommitter
        branch: ${GITHUB_REF##*/}
